/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Actions;

import ClasesOthers.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyFade;

/**
 *
 * @author Hello
 */
public class Seguro extends javax.swing.JFrame {

    /**
     * Creates new form Seguro
     */
    public Seguro() {
         setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_shipping = new javax.swing.JLabel();
        numpoliza = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechainicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vencimiento = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnAgregar = new java.awt.Button();
        cancelar = new java.awt.Button();
        jLabel14 = new javax.swing.JLabel();
        beneficiario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(790, 590));
        jPanel1.setMinimumSize(new java.awt.Dimension(790, 590));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_shipping.setFont(new java.awt.Font("Decker", 1, 16)); // NOI18N
        lbl_shipping.setForeground(new java.awt.Color(102, 102, 102));
        lbl_shipping.setText("REGISTRO");
        lbl_shipping.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_shippingMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_shipping, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -3, 169, 40));

        numpoliza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numpoliza.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        numpoliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numpolizaActionPerformed(evt);
            }
        });
        numpoliza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                numpolizaKeyTyped(evt);
            }
        });
        jPanel1.add(numpoliza, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 152, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel4.setText("Número de poliza");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 130, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setText("Fecha de Inicio");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        fechainicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechainicio.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        fechainicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechainicioActionPerformed(evt);
            }
        });
        jPanel1.add(fechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 145, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel6.setText("Vencimiento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        vencimiento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vencimiento.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        vencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vencimientoActionPerformed(evt);
            }
        });
        jPanel1.add(vencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 145, 33));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 790, 10));

        btnAgregar.setActionCommand("btn_complete");
        btnAgregar.setBackground(new java.awt.Color(36, 193, 93));
        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setLabel("Guardar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 180, 33));

        cancelar.setActionCommand("btn_cancel");
        cancelar.setBackground(new java.awt.Color(255, 0, 51));
        cancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setLabel("Cancelar ");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 180, 33));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel14.setText("Beneficiario");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, -1, -1));

        beneficiario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        beneficiario.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        beneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beneficiarioActionPerformed(evt);
            }
        });
        beneficiario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                beneficiarioKeyTyped(evt);
            }
        });
        jPanel1.add(beneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 145, 33));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px_1.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_shippingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_shippingMouseClicked
        // TODO add your handling code here:
        // lbl_shipping.setFont();
        lbl_shipping.setForeground(java.awt.Color.black);
    }//GEN-LAST:event_lbl_shippingMouseClicked

    private void numpolizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numpolizaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numpolizaActionPerformed

    private void fechainicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechainicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechainicioActionPerformed

    private void vencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vencimientoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

         try {
         //  int a = Integer.parseInt(id.getText());
           PreparedStatement pat = cn.prepareStatement("INSERT INTO seguro(noPoliza,beneficiario,fechaCont,vencimiento) VALUES(?,?,?,?)");
          
          // pat.setInt(1, a);
           pat.setString(1, numpoliza.getText());
           pat.setString(2, fechainicio.getText());
           pat.setString(3, vencimiento.getText());
           pat.setString(4, beneficiario.getText());
          
           pat.executeUpdate();
            new rojerusan.RSNotifyFade("¡AGREGADO!", "SE HA AGREGADO UN NUEVO SEGURO A LA BASE DE DATOS",
                    3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
           
//           id.setText("");
           numpoliza.setText("");
           fechainicio.setText("");
           vencimiento.setText("");
           beneficiario.setText("");
          

        } catch (SQLException ex) {
             new rojerusan.RSNotifyFade("¡ERROR!", "NO SE HA PODIDO AGREGAR, VERIFIQUE SUS DATOS",
                    4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);

       }
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here: evento de regreso al menu principal
      
//           id.setText("");
           numpoliza.setText("");
           fechainicio.setText("");
           vencimiento.setText("");
           beneficiario.setText("");
          
    }//GEN-LAST:event_cancelarActionPerformed

    private void beneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beneficiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beneficiarioActionPerformed

    private void numpolizaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numpolizaKeyTyped
         char validar = evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar números");
        }
           int pValor = 13;
        if (numpoliza.getText().length()>=pValor)
      {
       evt.consume();
       
                          JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
      }
    }//GEN-LAST:event_numpolizaKeyTyped

    private void beneficiarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_beneficiarioKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(!Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar letras");
        }
    }//GEN-LAST:event_beneficiarioKeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked

        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seguro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seguro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beneficiario;
    private java.awt.Button btnAgregar;
    private java.awt.Button cancelar;
    private javax.swing.JTextField fechainicio;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_shipping;
    private javax.swing.JTextField numpoliza;
    private javax.swing.JTextField vencimiento;
    // End of variables declaration//GEN-END:variables
ConexionBD cc = new ConexionBD();
    Connection cn = cc.getConnection();
}
