/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Update;

import Actions.*;
import ClasesOthers.ConexionBD;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyFade;

/**
 *
 * @author Hello
 */
public class ChoferUpdate extends javax.swing.JFrame {

    /**
     * Creates new form Persona
     */
    public ChoferUpdate() {
         setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        am = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        curp = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        antiguedad = new javax.swing.JTextField();
        status = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        escolaridad = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        domicilio = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        noLicencia = new javax.swing.JTextField();
        teleme = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tipoLicencia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        fechan = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBusqueda = new rojeru_san.RSMTextFull();
        buscar = new javax.swing.JLabel();
        btnActualizar = new java.awt.Button();
        cancelar = new java.awt.Button();
        txtid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(790, 590));
        jPanel1.setMinimumSize(new java.awt.Dimension(790, 590));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel4.setText("Nombre(s)");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, 20));

        nombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 145, 33));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setText("Apellido Paterno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, -1, -1));

        ap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ap.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        ap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apActionPerformed(evt);
            }
        });
        ap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apKeyTyped(evt);
            }
        });
        jPanel1.add(ap, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 145, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel6.setText("Apellido Materno");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        am.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        am.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        am.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amActionPerformed(evt);
            }
        });
        am.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amKeyTyped(evt);
            }
        });
        jPanel1.add(am, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 145, 33));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel14.setText("Curp");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, -1, -1));

        curp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        curp.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        curp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                curpActionPerformed(evt);
            }
        });
        curp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                curpKeyTyped(evt);
            }
        });
        jPanel1.add(curp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 152, 33));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel19.setText("Antiguedad");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, -1, -1));

        antiguedad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        antiguedad.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        antiguedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiguedadActionPerformed(evt);
            }
        });
        antiguedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                antiguedadKeyTyped(evt);
            }
        });
        jPanel1.add(antiguedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 145, 33));

        status.setBackground(new java.awt.Color(222, 184, 135));
        status.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Activo", "Inactivo" }));
        status.setToolTipText("");
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 150, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel12.setText("Status");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        escolaridad.setBackground(new java.awt.Color(222, 184, 135));
        escolaridad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        escolaridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Preescolar", "Primaria", "Secundaria", "Bachillerato", "Licenciatura" }));
        escolaridad.setToolTipText("");
        escolaridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolaridadActionPerformed(evt);
            }
        });
        jPanel1.add(escolaridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 150, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel18.setText("Escolaridad");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel15.setText("Sexo");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        sexo.setBackground(new java.awt.Color(222, 184, 135));
        sexo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Femenino", "Masculino" }));
        sexo.setToolTipText("");
        sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sexoActionPerformed(evt);
            }
        });
        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 150, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel7.setText("Domicilio");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        domicilio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        domicilio.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        domicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domicilioActionPerformed(evt);
            }
        });
        jPanel1.add(domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 145, 33));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel20.setText("No.Licencia");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 90, -1));

        noLicencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        noLicencia.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        noLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noLicenciaActionPerformed(evt);
            }
        });
        noLicencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                noLicenciaKeyTyped(evt);
            }
        });
        jPanel1.add(noLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 145, 33));

        teleme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teleme.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        teleme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telemeActionPerformed(evt);
            }
        });
        teleme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telemeKeyTyped(evt);
            }
        });
        jPanel1.add(teleme, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 160, 33));

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel22.setText("Telefono de emergencia");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 170, -1));

        tipoLicencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipoLicencia.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        tipoLicencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoLicenciaActionPerformed(evt);
            }
        });
        tipoLicencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tipoLicenciaKeyTyped(evt);
            }
        });
        jPanel1.add(tipoLicencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 145, 33));

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel21.setText("Tipo de licencia");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 130, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel23.setText("Fechan");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 90, -1));

        fechan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fechan.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        fechan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechanActionPerformed(evt);
            }
        });
        jPanel1.add(fechan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 145, 33));

        telefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefono.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });
        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 145, 33));

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel24.setText("Num. Telefonico");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px_1.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 30));

        txtBusqueda.setPlaceholder("Buscar registro para actualización");
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar3.png"))); // NOI18N
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarKeyPressed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 50));

        btnActualizar.setActionCommand("btn_complete");
        btnActualizar.setBackground(new java.awt.Color(36, 193, 93));
        btnActualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setLabel("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 180, 33));

        cancelar.setActionCommand("btn_cancel");
        cancelar.setBackground(new java.awt.Color(255, 0, 51));
        cancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setLabel("Cancelar ");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 180, 33));

        txtid.setEditable(false);
        txtid.setBorder(null);
        txtid.setEnabled(false);
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        // TODO add your handling code here:
        int pValor = 10;
        if (nombre.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }

        char validar = evt.getKeyChar();
        if(!Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar letras");
        }
    }//GEN-LAST:event_nombreKeyTyped

    private void apActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apActionPerformed

    private void apKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apKeyTyped
        // TODO add your handling code here:
        int pValor = 10;
        if (ap.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }

        char c=evt.getKeyChar();

        if(Character.isDigit(c)) {
            getToolkit().beep();

            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar letras");
            //Error.setText("Ingresa Solo Letras";

            }
    }//GEN-LAST:event_apKeyTyped

    private void amActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amActionPerformed

    private void amKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amKeyTyped
        // TODO add your handling code here:
        int pValor = 10;
        if (am.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }

        char validar = evt.getKeyChar();
        if(!Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar letras");
        }
    }//GEN-LAST:event_amKeyTyped

    private void curpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_curpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_curpActionPerformed

    private void curpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_curpKeyTyped
        // TODO add your handling code here:
        int pValor = 18;
        if (curp.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }
    }//GEN-LAST:event_curpKeyTyped

    private void antiguedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiguedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiguedadActionPerformed

    private void antiguedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_antiguedadKeyTyped
        // TODO add your handling code here:

        int pValor = 15;
        if (antiguedad.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }
    }//GEN-LAST:event_antiguedadKeyTyped

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void escolaridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolaridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_escolaridadActionPerformed

    private void sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sexoActionPerformed

    private void domicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_domicilioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_domicilioActionPerformed

    private void noLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noLicenciaActionPerformed

    private void noLicenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_noLicenciaKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar números");
        }
        int pValor = 8;
        if (noLicencia.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }
    }//GEN-LAST:event_noLicenciaKeyTyped

    private void telemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telemeActionPerformed

    private void telemeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telemeKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar números");
        }
        int pValor = 13;
        if (teleme.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }
    }//GEN-LAST:event_telemeKeyTyped

    private void tipoLicenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoLicenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoLicenciaActionPerformed

    private void tipoLicenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tipoLicenciaKeyTyped
        // TODO add your handling code here:

        int pValor = 8;
        if (tipoLicencia.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }
    }//GEN-LAST:event_tipoLicenciaKeyTyped

    private void fechanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechanActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane,"solo se pueden ingresar números");
        }
        int pValor = 12;
        if (telefono.getText().length()>=pValor)
        {
            evt.consume();

            JOptionPane.showMessageDialog(null,"limite de acaracteres excedido");
        }
    }//GEN-LAST:event_telefonoKeyTyped

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try{

                PreparedStatement pat = cn.prepareStatement("SELECT * FROM chofer WHERE  nombre= ?");
                pat.setString(1, txtBusqueda.getText());
  // estatus,antiguedad,noLicencia,tipoLicencia,nombre,ap,am,fechan,curp,domicilio,telefono,telefonoe,escolaridad,sexo
      
                ResultSet rs = pat.executeQuery();
                if(rs.next()){
                    txtid.setText(rs.getString("idChofer"));
                    status.setSelectedItem(rs.getString("estatus"));
                    antiguedad.setText(rs.getString("antiguedad"));
                    noLicencia.setText(rs.getString("noLicencia"));
                    tipoLicencia.setText(rs.getString("tipoLicencia"));
                    nombre.setText(rs.getString("nombre"));
                    ap.setText(rs.getString("ap"));
                    am.setText(rs.getString("am"));
                    fechan.setText(rs.getString("fechan"));
                    curp.setText(rs.getString("curp"));
                    domicilio.setText(rs.getString("domicilio"));
                    telefono.setText(rs.getString("telefono"));
                    teleme.setText(rs.getString("telefonoe"));
                    escolaridad.setSelectedItem(rs.getString("escolaridad"));
                    sexo.setSelectedItem(rs.getString("sexo"));
                    
                    
                    
                } else {
                    JOptionPane.showMessageDialog(null, "No existe el registro que está buscando o verifique que este bien escrita su busqueda");

                }

            } catch(Exception e){
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked

    }//GEN-LAST:event_buscarMouseClicked

    private void buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarKeyPressed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
                                                            try {
            PreparedStatement pat = cn.prepareStatement("UPDATE chofer  SET estatus=?, antiguedad=?, noLicencia=?, tipoLicencia=?, nombre=?, ap=?, am=?, fechan=?, curp=?, domicilio=?, telefono=?, telefonoe=?, escolaridad=?, sexo=? WHERE idChofer=?");

           pat.setString(1, status.getSelectedItem().toString());
           pat.setString(2, antiguedad.getText());
           pat.setString(3, noLicencia.getText());
           pat.setString(4, tipoLicencia.getText());
           pat.setString(5, nombre.getText());
           pat.setString(6, ap.getText());
           pat.setString(7, am.getText());
           pat.setString(8, fechan.getText());
           pat.setString(9, curp.getText());
           pat.setString(10, domicilio.getText());
           pat.setString(11,telefono.getText());
           pat.setString(12,teleme.getText());
           pat.setString(13,escolaridad.getSelectedItem().toString());
           pat.setString(14,sexo.getSelectedItem().toString());
           pat.setString(15,txtid.getText());

            int res = pat.executeUpdate();

            if(res > 0)
            {
                new rojerusan.RSNotifyFade("¡ACTUALIZADO!", "SE HA ACTUALIZADO ESTE REGISTRO",
                    3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                status.setSelectedIndex(0);
           antiguedad.setText("");
           noLicencia.setText("");
           tipoLicencia.setText("");
           nombre.setText("");
           ap.setText("");
           am.setText("");
           fechan.setText("");
           curp.setText("");
           domicilio.setText("");
           telefono.setText("");
           escolaridad.setSelectedIndex(0);
           sexo.setSelectedIndex(0);
            teleme.setText("");
           
            }
            else
            {
                new rojerusan.RSNotifyFade("¡ERROR!", "NO SE HA PODIDO ACTUALIZAR, VERIFIQUE SUS DATOS",
                    4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }

        } catch (Exception e) {
            new rojerusan.RSNotifyFade("¡ERROR!", "",
                4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);

        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here: evento de regreso al menu principal
        status.setSelectedIndex(0);
           antiguedad.setText("");
           noLicencia.setText("");
           tipoLicencia.setText("");
           nombre.setText("");
           ap.setText("");
           am.setText("");
           fechan.setText("");
           curp.setText("");
           domicilio.setText("");
           telefono.setText("");
           escolaridad.setSelectedIndex(0);
           sexo.setSelectedIndex(0);
           teleme.setText("");

    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoferUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoferUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoferUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoferUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoferUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField am;
    private javax.swing.JTextField antiguedad;
    private javax.swing.JTextField ap;
    private java.awt.Button btnActualizar;
    private javax.swing.JLabel buscar;
    private java.awt.Button cancelar;
    private javax.swing.JTextField curp;
    private javax.swing.JTextField domicilio;
    private javax.swing.JComboBox<String> escolaridad;
    private javax.swing.JTextField fechan;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField noLicencia;
    private javax.swing.JTextField nombre;
    private javax.swing.JComboBox<String> sexo;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField teleme;
    private javax.swing.JTextField tipoLicencia;
    private rojeru_san.RSMTextFull txtBusqueda;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
ConexionBD cc = new ConexionBD();
    Connection cn = cc.getConnection();
}
