

package Update;

import Actions.*;
import ClasesOthers.ConexionBD;
import Frame.Menus;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.*;
import javax.swing.JOptionPane;
import rojerusan.RSNotifyFade;

/**
 *
 * @author Hello
 */
public class VehiculoUpdate extends javax.swing.JFrame {

    /**
     * Creates new form Vehiculo
     */
    public VehiculoUpdate() {
         setUndecorated(true);
        initComponents();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelar = new java.awt.Button();
        btnActualizar = new java.awt.Button();
        txtBusqueda = new rojeru_san.RSMTextFull();
        buscar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nummotor = new javax.swing.JTextField();
        numplacas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        capacidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        numsitio = new javax.swing.JTextField();
        observaciones = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        modelo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        numserie = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        color = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        numunico = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(790, 590));
        jPanel1.setMinimumSize(new java.awt.Dimension(790, 590));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelar.setActionCommand("btn_cancel");
        cancelar.setBackground(new java.awt.Color(255, 0, 51));
        cancelar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cancelar.setForeground(new java.awt.Color(255, 255, 255));
        cancelar.setLabel("Cancelar ");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 180, 33));

        btnActualizar.setActionCommand("btn_complete");
        btnActualizar.setBackground(new java.awt.Color(36, 193, 93));
        btnActualizar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setLabel("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 180, 33));

        txtBusqueda.setPlaceholder("Buscar registro para actualización");
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });
        jPanel1.add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, -1));

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar3.png"))); // NOI18N
        buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarMouseClicked(evt);
            }
        });
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarKeyPressed(evt);
            }
        });
        jPanel1.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 50, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setText("Número de motor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        nummotor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nummotor.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        nummotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nummotorActionPerformed(evt);
            }
        });
        jPanel1.add(nummotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 145, 33));

        numplacas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numplacas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        numplacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numplacasActionPerformed(evt);
            }
        });
        jPanel1.add(numplacas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 33));

        jLabel13.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel13.setText("Numero de placas");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel7.setText("Capacidad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        capacidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capacidad.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        capacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacidadActionPerformed(evt);
            }
        });
        jPanel1.add(capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 33));

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel12.setText("Numero de sitio");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        numsitio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numsitio.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        numsitio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numsitioActionPerformed(evt);
            }
        });
        jPanel1.add(numsitio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, 33));

        observaciones.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        observaciones.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        observaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observacionesActionPerformed(evt);
            }
        });
        jPanel1.add(observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 150, 33));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel8.setText("Observaciones");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        modelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modelo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloActionPerformed(evt);
            }
        });
        jPanel1.add(modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 145, 33));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel16.setText("Modelo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        numserie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numserie.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        numserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numserieActionPerformed(evt);
            }
        });
        jPanel1.add(numserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 145, 33));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel6.setText("Número de serie");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel14.setText("Tipo");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));

        tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        jPanel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 145, 33));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel10.setText("Color");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, -1, -1));

        color.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        color.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorActionPerformed(evt);
            }
        });
        jPanel1.add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 145, 33));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel9.setText("Numero Unico");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        numunico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numunico.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, null));
        numunico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numunicoActionPerformed(evt);
            }
        });
        jPanel1.add(numunico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 150, 33));

        txtid.setEditable(false);
        txtid.setBorder(null);
        txtid.setEnabled(false);
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 40, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px_1.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here: evento de regreso al menu principal
        modelo.setText("");
        nummotor.setText("");
        numplacas.setText("");
        numserie.setText("");
        numsitio.setText("");
        numunico.setText("");
        observaciones.setText("");
        tipo.setText("");
        color.setText("");
        capacidad.setText("");

        
    }//GEN-LAST:event_cancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        try {                                                                   
            PreparedStatement pat = cn.prepareStatement("UPDATE vehiculo  SET numPlacas=?, capacidad=?, observaciones=?, numSitio=?, tipo=?, modelo=?, noMotor=?, noSerie=?, color=?, numUnico=? WHERE idVehiculo=?");

            pat.setString(1, numplacas.getText());
            pat.setString(2, capacidad.getText());
            pat.setString(3, observaciones.getText());
            pat.setString(4, numsitio.getText());
            pat.setString(5, tipo.getText());
            pat.setString(6, modelo.getText());
            pat.setString(7, nummotor.getText());
            pat.setString(8, numserie.getText());
            pat.setString(9, color.getText());
            pat.setString(10,numunico.getText());
            pat.setString(11,txtid.getText());

            int res = pat.executeUpdate();

            if(res > 0)
            {
                new rojerusan.RSNotifyFade("¡ACTUALIZADO!", "SE HA ACTUALIZADO ESTE REGISTRO",
                    3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
        modelo.setText("");
        nummotor.setText("");
        numplacas.setText("");
        numserie.setText("");
        numsitio.setText("");
        numunico.setText("");
        observaciones.setText("");
        tipo.setText("");
        color.setText("");
        capacidad.setText("");

            }
            else
            {
                new rojerusan.RSNotifyFade("¡ERROR!", "NO SE HA PODIDO ACTUALIZAR, VERIFIQUE SUS DATOS",
                    4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }

        } catch (Exception e) {
            new rojerusan.RSNotifyFade("¡ERROR!", "",
                4, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);

            
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            try{

                PreparedStatement pat = cn.prepareStatement("SELECT * FROM vehiculo WHERE  numSitio= ?");
                pat.setString(1, txtBusqueda.getText());

                ResultSet rs = pat.executeQuery();
               if(rs.next()){
                    txtid.setText(rs.getString("idVehiculo"));
                    numplacas.setText(rs.getString("NumPlacas"));
                    capacidad.setText(rs.getString("capacidad"));
                    observaciones.setText(rs.getString("observaciones"));
                    numsitio.setText(rs.getString("numSitio"));
                    tipo.setText(rs.getString("tipo"));
                    modelo.setText(rs.getString("modelo"));
                    nummotor.setText(rs.getString("noMotor"));
                    numserie.setText(rs.getString("noSerie"));
                    color.setText(rs.getString("color"));
                    numunico.setText(rs.getString("numUnico"));
                } else {
                    JOptionPane.showMessageDialog(null, "No existe el registro que está buscando o verifique que este bien escrita su busqueda");

                }

            } catch(Exception e){
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseClicked
        
    }//GEN-LAST:event_buscarMouseClicked

    private void buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarKeyPressed

    private void nummotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nummotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nummotorActionPerformed

    private void numplacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numplacasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numplacasActionPerformed

    private void capacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadActionPerformed

    private void numsitioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numsitioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numsitioActionPerformed

    private void observacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observacionesActionPerformed

    private void modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloActionPerformed

    private void numserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numserieActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorActionPerformed

    private void numunicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numunicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numunicoActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehiculoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehiculoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehiculoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehiculoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehiculoUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnActualizar;
    private javax.swing.JLabel buscar;
    private java.awt.Button cancelar;
    private javax.swing.JTextField capacidad;
    private javax.swing.JTextField color;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nummotor;
    private javax.swing.JTextField numplacas;
    private javax.swing.JTextField numserie;
    private javax.swing.JTextField numsitio;
    private javax.swing.JTextField numunico;
    private javax.swing.JTextField observaciones;
    private javax.swing.JTextField tipo;
    private rojeru_san.RSMTextFull txtBusqueda;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
ConexionBD cc = new ConexionBD();
    Connection cn = cc.getConnection();
}
