/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;
import Actions.Chofer;
import Actions.Concesion;

import Actions.Seguro;
import Actions.Socio;
import Actions.Vehiculo;
import ClasesOthers.CambiaPanel;
import Update.ChoferUpdate;
//import Update.DirectivoUpdate;
import Update.SocioUpdate;
import Update.VehiculoUpdate;


/**
 *
 * @author Hello
 */
public class CambioUpdate extends javax.swing.JPanel {

    /**
     * Creates new form CambioAdd
     */
    public CambioUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        choferr = new javax.swing.JLabel();
        vehiculo = new rojeru_san.RSButton();
        socio = new rojeru_san.RSButton();
        chofer = new rojeru_san.RSButton();
        Vehiculo = new javax.swing.JLabel();
        soci = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(990, 470));
        setMinimumSize(new java.awt.Dimension(990, 470));
        setPreferredSize(new java.awt.Dimension(1350, 898));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 898));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-restart-128.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 320, -1, -1));

        choferr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/people.png"))); // NOI18N
        choferr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choferr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choferrMouseClicked(evt);
            }
        });
        jPanel1.add(choferr, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, 80));

        vehiculo.setBackground(new java.awt.Color(255, 255, 255));
        vehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        vehiculo.setText("VEHICULO");
        vehiculo.setColorText(new java.awt.Color(0, 0, 0));
        vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 150, 30));

        socio.setBackground(new java.awt.Color(255, 255, 255));
        socio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        socio.setText("SOCIO");
        socio.setColorText(new java.awt.Color(0, 0, 0));
        socio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socioActionPerformed(evt);
            }
        });
        jPanel1.add(socio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 150, 30));

        chofer.setBackground(new java.awt.Color(255, 255, 255));
        chofer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        chofer.setText("CHOFER");
        chofer.setColorText(new java.awt.Color(0, 0, 0));
        chofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choferActionPerformed(evt);
            }
        });
        jPanel1.add(chofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 150, 30));

        Vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/taximenu.png"))); // NOI18N
        Vehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehiculoMouseClicked(evt);
            }
        });
        jPanel1.add(Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, 80));

        soci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/people.png"))); // NOI18N
        soci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        soci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sociMouseClicked(evt);
            }
        });
        jPanel1.add(soci, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, 80));

        jLabel9.setFont(new java.awt.Font("Moon", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineas-blancas-60.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choferActionPerformed
        ChoferUpdate pa = new ChoferUpdate();
        pa.setVisible(true);
    }//GEN-LAST:event_choferActionPerformed

    private void vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculoActionPerformed
        // TODO add your handling code here:
          VehiculoUpdate v = new VehiculoUpdate();
          v.setVisible(true);
    }//GEN-LAST:event_vehiculoActionPerformed

    private void VehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiculoMouseClicked
    
    }//GEN-LAST:event_VehiculoMouseClicked

    private void sociMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sociMouseClicked
      
    }//GEN-LAST:event_sociMouseClicked

    private void socioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socioActionPerformed
        // TODO add your handling code here:
          SocioUpdate pq = new SocioUpdate();
        pq.setVisible(true);
    }//GEN-LAST:event_socioActionPerformed

    private void choferrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choferrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choferrMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Vehiculo;
    private rojeru_san.RSButton chofer;
    private javax.swing.JLabel choferr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel soci;
    private rojeru_san.RSButton socio;
    private rojeru_san.RSButton vehiculo;
    // End of variables declaration//GEN-END:variables
}
