/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paneles;
import Actions.Chofer;
import Actions.Concesion;
//import Actions.DirectivoDelete;
//import Actions.Chofe;
import Actions.Seguro;
import Actions.Socio;
import Actions.Vehiculo;
import ClasesOthers.CambiaPanel;
import Delete.ChoferDelete;
import Delete.ConcesionDelete;
import Delete.SeguroDelete;
import Delete.VehiculoDelete;
//import Delete.DirectivoDelete;


/**
 *
 * @author Hello
 */
public class CambioDelete extends javax.swing.JPanel {

    /**
     * Creates new form CambioAdd
     */
    public CambioDelete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        choferr = new javax.swing.JLabel();
        seguro = new rojeru_san.RSButton();
        vehiculo = new rojeru_san.RSButton();
        concesion = new rojeru_san.RSButton();
        chofer = new rojeru_san.RSButton();
        Vehiculo = new javax.swing.JLabel();
        Seguro = new javax.swing.JLabel();
        Concesion = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(990, 470));
        setMinimumSize(new java.awt.Dimension(990, 470));
        setPreferredSize(new java.awt.Dimension(1350, 898));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(990, 470));
        jPanel1.setMinimumSize(new java.awt.Dimension(990, 470));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 898));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8-trash-can-128.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 310, -1, -1));

        choferr.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/people.png"))); // NOI18N
        choferr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        choferr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                choferrMouseClicked(evt);
            }
        });
        jPanel1.add(choferr, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, 80));

        seguro.setBackground(new java.awt.Color(255, 255, 255));
        seguro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        seguro.setText("SEGURO");
        seguro.setColorText(new java.awt.Color(0, 0, 0));
        seguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguroActionPerformed(evt);
            }
        });
        jPanel1.add(seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 150, 30));

        vehiculo.setBackground(new java.awt.Color(255, 255, 255));
        vehiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        vehiculo.setText("VEHICULO");
        vehiculo.setColorText(new java.awt.Color(0, 0, 0));
        vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 150, 30));

        concesion.setBackground(new java.awt.Color(255, 255, 255));
        concesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        concesion.setText("CONCESION");
        concesion.setColorText(new java.awt.Color(0, 0, 0));
        concesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concesionActionPerformed(evt);
            }
        });
        jPanel1.add(concesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 150, 30));

        chofer.setBackground(new java.awt.Color(255, 255, 255));
        chofer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        chofer.setText("CHOFER");
        chofer.setColorText(new java.awt.Color(0, 0, 0));
        chofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choferActionPerformed(evt);
            }
        });
        jPanel1.add(chofer, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 150, 30));

        Vehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/taximenu.png"))); // NOI18N
        Vehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VehiculoMouseClicked(evt);
            }
        });
        jPanel1.add(Vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 165, -1, 80));

        Seguro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/safe.png"))); // NOI18N
        Seguro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seguro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeguroMouseClicked(evt);
            }
        });
        jPanel1.add(Seguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 165, -1, 80));

        Concesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/concesion.png"))); // NOI18N
        Concesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Concesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConcesionMouseClicked(evt);
            }
        });
        jPanel1.add(Concesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, -1, 80));

        jLabel9.setFont(new java.awt.Font("Moon", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lineas-blancas-60.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void choferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choferActionPerformed
        ChoferDelete pa = new ChoferDelete();
        pa.setVisible(true);
    }//GEN-LAST:event_choferActionPerformed

    private void seguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguroActionPerformed
        // TODO add your handling code here:
         SeguroDelete sa= new SeguroDelete();
        sa.setVisible(true);
    }//GEN-LAST:event_seguroActionPerformed

    private void vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiculoActionPerformed
        // TODO add your handling code here:
          VehiculoDelete v = new VehiculoDelete();
      v.setVisible(true);
    }//GEN-LAST:event_vehiculoActionPerformed

    private void concesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concesionActionPerformed
        // TODO add your handling code here:
        ConcesionDelete c = new ConcesionDelete();
        c.setVisible(true);
    }//GEN-LAST:event_concesionActionPerformed

    private void VehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VehiculoMouseClicked
    
    }//GEN-LAST:event_VehiculoMouseClicked

    private void SeguroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeguroMouseClicked
       
    }//GEN-LAST:event_SeguroMouseClicked

    private void ConcesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConcesionMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ConcesionMouseClicked

    private void choferrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_choferrMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_choferrMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Concesion;
    private javax.swing.JLabel Seguro;
    private javax.swing.JLabel Vehiculo;
    private rojeru_san.RSButton chofer;
    private javax.swing.JLabel choferr;
    private rojeru_san.RSButton concesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSButton seguro;
    private rojeru_san.RSButton vehiculo;
    // End of variables declaration//GEN-END:variables
}
